### PR TITLE
fixes for infortrend disks check

### PR DESCRIPTION
**Pull request by stefan927**
fixed wrong oid.

fix disk discovery & check for infortrend boxes with JBOD extensions:
we have some infortrend boxes with JBOD extension, these where missing the disk checks due that the disk number goes back to 0 instead of counting it the right way.

remove disk slot 0 (which is no valid disk slot).

### CODE REVIEW

**Comment by gurubert** [comment]
If the OID changes, a new check should be implemented. There are devices out there where the "old" OID is valid. Infortrend may have changed the SNMP Agent.

**Comment by stefan927** [comment]
alright, let me change the PR. i thought that was just a c&p failure :D

**Comment by comhelge** [comment]
I am looking for a check_MK support for infotrend storage on these checks and have also tried them. However, in all 3 checks the oids in the scan function did not. Furthermore, I have changed the interpretation of the rc for "drive absent" in the disks check, as well as the logical drive status status 64 in check ldrives. However, some services still have a "Max recursion depth reached" error. Could someone ever look at it? How can I support?

**Comment by gurubert** [comment]
Hi @comhelge ,
we can offer professional support if you live within the EU or Switzerland. In that case please send an email to support@heinlein-support.de and we will answer shortly.
Regards

**Comment by comhelge** [comment]
Have you sent the desired email just now.

**Pull request closed without merging**
