### PR TITLE
added 'active+recovery_wait+degraded+remapped'

### PR DESCRIPTION
**Pull request by HenriWahl**
Found another one by getting "KeyError (u'active+recovery_wait+degraded+remapped')"

### CODE REVIEW

**Comment by HenriWahl** [comment]
found next one from KeyError (u'remapped+peering')

**Comment by HenriWahl** [comment]
Found KeyError (u'undersized+degraded+peered')

**Comment by HenriWahl** [comment]
Found KeyError (u'active+recovery_wait+undersized+degraded')

**Comment by HenriWahl** [comment]
Found KeyError (u'active+clean+remapped')

**Comment by gurubert** [comment]
Hi Henri,
please add the new pgstate also in web/plugins/metrics/ceph.py and create a new MKP (with version 5.7 as of now).

**Comment by HenriWahl** [comment]
Added new states to ceph.py

**Pull request merged**
